[package]
name = "lili"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
lili-lib = { path = "lili-lib" }
